apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ns.yaml
  - ./gw.yaml

helmCharts:
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.25.2
    namespace: istio-ingress
    releaseName: istio-ingressgateway