apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-loop
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/bash", "-c"]
    args: ["while true; do sleep 1s; done"]
    tty: true
