apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingress-gw
spec:
  selector:
    istio: ingressgateway # default ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "argocd.172.18.1.0.nip.io"
