apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: hello-world
    repo: https://helm.github.io/examples
    version: 0.1.0
    releaseName: helloworld
    namespace: default
