apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  applicationsetcontroller.log.level: "debug"
  applicationsetcontroller.debug: "true"
  applicationsetcontroller.dryrun: "true"