apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: tigera-operator
    repo: https://docs.tigera.io/calico/charts
    version: 3.30.0
    releaseName: calico
    namespace: tigera-operator
    includeCRDs: true

patches:
  - path: patch/custom-resources.yaml
