apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ns.yaml

helmCharts:
  - name: argo-cd
    repo: oci://ghcr.io/argoproj/argo-helm
    version: 8.0.0
    releaseName: argocd
    namespace: argocd
    includeCRDs: true

patches:
  - path: patch/argocd-cm.yaml
