apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: details
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minhtrietbkit/argo-gitops-demo
    targetRevision: HEAD
    path: helm-charts/details
  destination:
    server: "https://172.18.0.7:6443"
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true