apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-shared-ingressgateway
spec:
  selector:
    istio: ingressgateway # default ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "productpage.172.18.1.1.nip.io"
