apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 72.3.0
    releaseName: prometheus-grafana-stack
    includeCRDs: true
    valuesInline:
      grafana:
        enabled: true
        defaultDashboardsTimezone: browser
        adminUser: admin
        adminPassword: adminadmin
      prometheus:
        prometheusSpec:
          serviceMonitorSelectorNilUsesHelmValues: false

