apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.9.0
    helm:
      releaseName: argo-cd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-cd