apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
    - "productpage.127.0.0.1.nip.io"
  gateways:
    - istio-ingress/istio-shared-ingressgateway
  http:
    - route:
        - destination:
            host: productpage
            port:
              number: 9080