apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
    - "productpage.172.18.1.0.nip.io""
  gateways:
    - istio-shared-ingressgateway
  http:
    - route:
        - destination:
            host: productpage
            port:
              number: 9080