apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev2
  namespace: argocd
spec:
  generators:
#    - git:
#        repoURL: https://github.com/minhtrietbkit/argo-gitops-demo
#        revision: HEAD
#        files:
#          - path: "environments/dev/**/clusterconfig.json"
#    - matrix:
#        generators:
#          # Cluster-level info (e.g., cluster server)
#          - git:
#              repoURL: https://github.com/minhtrietbkit/argo-gitops-demo
#              revision: HEAD
#              files:
#                - path: "environments/dev/**/clusterconfig.json"
#              pathParamPrefix: "cluster"
#          # Service-level config, which includes clusterName to match
#          - git:
#              repoURL: https://github.com/minhtrietbkit/argo-gitops-demo
#              revision: HEAD
#              files:
##                - path: "{{.cluster.path}}/service*config.json"
#                - path: "{{.cluster.path.path}}/service_details_config.json"
#              pathParamPrefix: "service"
    - matrix:
        generators:
          - list:
              elements:
                - epath: cluster
                - epath: cluster2
          - git:
              repoURL: https://github.com/minhtrietbkit/argo-gitops-demo
              revision: HEAD
              files:
                - path: "environments/dev/{{.epath}}/service_details_config.json"
              pathParamPrefix: "service"
  template:
    metadata:
      name: '{{clusterName}}-{{name}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: default
      sources:
        - repoURL: '{{ repo }}'
          targetRevision: '{{targetRevision}}'
          path: '{{path}}'
          helm:
            valueFiles:
              - '{{valueFilePath}}'
        - repoURL: '{{valueFileRepo}}'
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{clusterHost}}'
        namespace: '{{namespace}}'